---
os: linux
language: python
python:
- "3.6"
- "3.7"
- "3.8"

git:
  depth: 2

cache: pip

branches:
  only:
  - stable
  - devel
  - /^[0-9]+\.[0-9]+\.[0-9]+[.0-9ab]*$/

env:
  global:
  - GITHUB_REPO=opencobra/cobrapy

install:
- python -m pip install --upgrade pip setuptools wheel tox tox-travis

script:
- tox -- --benchmark-skip --cov-report=xml
after_success:
- bash <(curl -s https://codecov.io/bash)

stages:
  - test
  - name: deploy
    if: tag IS present

jobs:
  fast_finish: true
  include:
  - stage: deploy
    python: "3.8"
    install:
    - python -m pip install --upgrade pip setuptools wheel
    script: skip
    after_success:
    - echo "Deploying..."
    deploy:
    - provider: pypi
      cleanup: false
      distributions: sdist bdist_wheel
      username: cobrapy
      password: $PYPI_PASSWORD
      on:
        tags: true
        repo: $GITHUB_REPO
    - provider: script
      cleanup: false
      script: scripts/deploy_website.sh
      on:
        tags: true
        repo: $GITHUB_REPO
    - provider: releases
      cleanup: false
      token: $GITHUB_TOKEN
      release_notes: "Please see https://github.com/opencobra/cobrapy/tree/${TRAVIS_TAG}/release-notes/${TRAVIS_TAG}.md for the full release notes."
      on:
        tags: true
        repo: $GITHUB_REPO

notifications:
  email:
    on_success: never
    on_failure: always
